/** Auto-generated by scripts/optimize-images.mjs — do not edit */
export const imageManifest = {
  "cafe-hafa": {
    "base": "cafe-hafa",
    "width": 4608,
    "height": 3456,
    "fallbackWidth": 800,
    "fallbackHeight": 600,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "cape-spartel": {
    "base": "cape-spartel",
    "width": 4080,
    "height": 3060,
    "fallbackWidth": 800,
    "fallbackHeight": 600,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "chefchaouen": {
    "base": "chefchaouen",
    "width": 3264,
    "height": 1836,
    "fallbackWidth": 800,
    "fallbackHeight": 450,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "coast": {
    "base": "coast",
    "width": 4080,
    "height": 3060,
    "fallbackWidth": 1920,
    "fallbackHeight": 1440,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "coastal": {
    "base": "coastal",
    "width": 4080,
    "height": 3060,
    "fallbackWidth": 1920,
    "fallbackHeight": 1440,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "compare": {
    "base": "compare",
    "width": 4288,
    "height": 2848,
    "fallbackWidth": 1920,
    "fallbackHeight": 1275,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "cruise-port": {
    "base": "cruise-port",
    "width": 4288,
    "height": 2848,
    "fallbackWidth": 1920,
    "fallbackHeight": 1275,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "family": {
    "base": "family",
    "width": 1536,
    "height": 1024,
    "fallbackWidth": 800,
    "fallbackHeight": 533,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "food": {
    "base": "food",
    "width": 3200,
    "height": 2400,
    "fallbackWidth": 800,
    "fallbackHeight": 600,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "food-and-wine": {
    "base": "food-and-wine",
    "width": 3200,
    "height": 2400,
    "fallbackWidth": 800,
    "fallbackHeight": 600,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "hercules-caves": {
    "base": "hercules-caves",
    "width": 2448,
    "height": 3264,
    "fallbackWidth": 800,
    "fallbackHeight": 1067,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "hero": {
    "base": "hero",
    "width": 3088,
    "height": 3088,
    "fallbackWidth": 1920,
    "fallbackHeight": 1920,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "hero-home": {
    "base": "hero-home",
    "width": 3088,
    "height": 3088,
    "fallbackWidth": 1920,
    "fallbackHeight": 1920,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "historic": {
    "base": "historic",
    "width": 2822,
    "height": 2136,
    "fallbackWidth": 800,
    "fallbackHeight": 606,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "kasbah": {
    "base": "kasbah",
    "width": 4471,
    "height": 5760,
    "fallbackWidth": 800,
    "fallbackHeight": 1031,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "markets": {
    "base": "markets",
    "width": 6000,
    "height": 4000,
    "fallbackWidth": 800,
    "fallbackHeight": 533,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "medina": {
    "base": "medina",
    "width": 2822,
    "height": 2136,
    "fallbackWidth": 800,
    "fallbackHeight": 606,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "nature": {
    "base": "nature",
    "width": 1800,
    "height": 1350,
    "fallbackWidth": 1800,
    "fallbackHeight": 1350,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "og-default": {
    "base": "og-default",
    "width": 3088,
    "height": 3088,
    "fallbackWidth": 1920,
    "fallbackHeight": 1920,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ],
    "og": {
      "width": 1200,
      "height": 630
    },
    "ogSrc": "/images/opt/og-default-og1200.jpg"
  },
  "photography": {
    "base": "photography",
    "width": 1920,
    "height": 2560,
    "fallbackWidth": 1920,
    "fallbackHeight": 2560,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "private": {
    "base": "private",
    "width": 4032,
    "height": 3024,
    "fallbackWidth": 800,
    "fallbackHeight": 600,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "viewpoints": {
    "base": "viewpoints",
    "width": 7919,
    "height": 4314,
    "fallbackWidth": 800,
    "fallbackHeight": 436,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "walking": {
    "base": "walking",
    "width": 2400,
    "height": 3200,
    "fallbackWidth": 800,
    "fallbackHeight": 1067,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "wine": {
    "base": "wine",
    "width": 3200,
    "height": 2400,
    "fallbackWidth": 800,
    "fallbackHeight": 600,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  }
} as const;

export type ImageManifestEntry = (typeof imageManifest)[keyof typeof imageManifest];
